project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 2024 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://SethKauf.github.io/STA9750-2024-FALL/"
  navbar:
    background: primary
    search: false
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: mp01.qmd
        href: mp02.qmd
    
format:
  html:
    theme: solar
    toc: false
    self-contained: true